name: "Eureka DevSecOps"
description: "Scan your code with Eureka DevSecOps to discover potential security risks and vulnerabilities"
inputs:
  synk_token:
    description: "Synk scanner API token"
    required: false
    default: ""
  sonarqube_user_token:
    description: "SonarQube user security token"
    required: false
    default: ""
  veracode_api_key_id:
    description: "Veracode SAST/SCA/Pipeline API key ID"
    required: false
    default: ""
  veracode_api_key_secret:
    description: "Veracode SAST/SCA/Pipeline API key secret"
    required: false
    default: ""
  zap_username:
    description: "ZAP API username"
    required: false
    default: ""
  zap_password:
    description: "ZAP API password"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Login to the Docker Registry
      shell: bash
      run: |
        docker login -u ${EUREKA_USER} -p ${EUREKA_PASSWORD} eurekahubprodagentacr.azurecr.io

    - name: Pull down Eureka container
      shell: bash
      run: |
        docker pull eurekahubprodagentacr.azurecr.io/fwdsec/eureka:latest

    - name: Run Eureka scan
      shell: bash
      run: |
        docker run --rm --network host \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v "$(pwd)":/home/repo \
          -e SNYK_TOKEN="${{ inputs.snyk_token }}" \
          -e SONAR_USER_TOKEN="${{ inputs.sonarqube_user_token }}" \
          -e VERACODE_API_KEY_ID="${{ inputs.veracode_api_key_id }}" \
          -e VERACODE_API_KEY_SECRET="${{ inputs.veracode_api_key_secret }}" \
          -e DAST_USERNAME="${{ inputs.zap_username }}" \
          -e DAST_PASSWORD="${{ inputs.zap_password }}" \
          -e DIND_USER_HOME="$(pwd)" \
          -e EUREKA_ENDPOINT="${EUREKA_ENDPOINT}" \
          -e EUREKA_USER="${EUREKA_USER}" \
          -e EUREKA_PASSWORD="${EUREKA_PASSWORD}" \
          -e PROFILE_INFO="${PROFILE_INFO}" \
          eurekahubprodagentacr.azurecr.io/fwdsec/eureka:latest
